- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: true

  - name: Instalando dependencias com pip(Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework

  - name: Iniciando projeto
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
    ignore_errors: true

  - name: Alterando hosts do settings
    lineinfile: 
      path: /home/ubuntu/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes